// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    // Intro
    "intro",

    // Accounts
    {
      type: "category",
      label: "پنل کاربری",
      link: { type: "doc", id: "accounts/accountsIntro" },
      items: [
        "accounts/accountsRegisterAndLogin",
        "accounts/accountsEmailVerfication",
        "accounts/accountsCart",
        "accounts/accountsInvoices",
        "accounts/accountsSupportTicket",
        "accounts/accountsChangePassword",
        "accounts/accountsChangeInformation",
        "accounts/accountsServiceTransfer",
      ],
    },

    // Servers
    {
      type: "category",
      label: "سرور ها",
      link: { type: "doc", id: "servers/serversIntro" },
      items: [
        {
          type: "category",
          label: "سرور اختصاصی",
          link: { type: "doc", id: "servers/dedicated/serversDedicatedIntro" },
          items: [
            "servers/dedicated/serversDedicatedOrder",
            "servers/dedicated/serversDedicatedOS",
            "servers/dedicated/serversDedicatedConsole",
            "servers/dedicated/serversDedicatedExtraIP",
            "servers/dedicated/serversDedicatedTraffic",
            "servers/dedicated/serversDedicatedDatacenters",
          ],
        },
        {
          type: "category",
          label: "سرور ابری",
          link: { type: "doc", id: "servers/cloud-server/serversCloudIntro" },
          items: [
            "servers/cloud-server/serversCloudInfo",
            "servers/cloud-server/serversCloudResources",
            "servers/cloud-server/serversCloudBandwidth",
            "servers/cloud-server/serversCloudConsole",
            "servers/cloud-server/serversCloudUpgrade",
            "servers/cloud-server/serversCloudChangeIP",
            "servers/cloud-server/serversCloudReinstallOS",
          ],
        },
        {
          type: "category",
          label: "سرور مجازی",
          link: { type: "doc", id: "servers/vps/serversVpsIntro" },
          items: [],
        },
      ],
    },

    // Hosts
    {
      type: "category",
      label: "هاست ها",
      link: { type: "doc", id: "hosts/hostsIntro" },
      items: [
        {
          type: "category",
          label: "هاست اشتراکی",
          link: { type: "doc", id: "hosts/shared/hostsSharedIntro" },
          items: [],
        },
        {
          type: "category",
          label: "هاست دانلود",
          link: { type: "doc", id: "hosts/download/hostsDownloadIntro" },
          items: [],
        },
        {
          type: "category",
          label: "هاست ایمیل",
          link: { type: "doc", id: "hosts/email/hostsEmailIntro" },
          items: [],
        },
      ],
    },
  ],
};

export default sidebars;
